### Index

GET http://localhost:3000/products?average

### Create

POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "dumbbells", 
  "price": 0, 
  "image_url": " ", 
  "description": " ",
  "quantity": 0
}

### Show 
GET http://localhost:3000/any_products/7

### Patch

PATCH http://localhost:3000/any_products/2
Content-Type: application/json

{
"price": "1400"
}

### Delete 

DELETE http://localhost:3000/any_products/6
